language: java
sudo: false
install: true

jdk:
- oraclejdk8
script:
- mvn --quiet clean install -Prun-code-coverage
- ./travis-sonarcloud.sh

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"